# Generated by Django 4.1.5 on 2023-01-16 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='employee_type',
        ),
    ]
