# Generated by Django 4.1.5 on 2023-01-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_employee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_type',
            field=models.CharField(choices=[('External', ' External'), ('Internal', 'Internal')], max_length=10),
        ),
    ]
